Repository nascentdigital/pm-kit, pull requests merged in 2020-07, with the labels that each got.

#7 feat(input): added inputmode, organized code
  README.md
  package-lock.json
  package.json
  packages/Checkbox/package-lock.json
  packages/Dropdown/package-lock.json
  packages/Input/Input.jsx
  packages/Input/Input.stories.js
  packages/Input/__tests__/Input.spec.jsx
  packages/Input/__tests__/__snapshots__/Input.spec.jsx.snap
Labels: enhancement

#11 docs(other): display props of each component and its description
  packages/Button/Button.jsx
  packages/Checkbox/Checkbox.jsx
  packages/Dropdown/Dropdown.jsx
  packages/Heading/Heading.jsx
  packages/Input/Input.jsx
  packages/Paragraph/Paragraph.jsx
  packages/Radio/Radio.jsx
Labels: documentation

#12 chore(deps): update jest monorepo to v26(major)
  package-lock.json
  package.json
  packages/Input/Input.jsx
  packages/Input/Input.stories.js
Labels: dependency

#17 fix(other): nascentdigital/pm-kit master with telus/pm-kit master
  packages/Card/CHANGELOG.md
  packages/Card/Card.jsx
  packages/Card/Card.stories.js
  packages/Card/__tests__/__snapshots__/Card.spec.jsx.snap
  packages/Card/package-lock.json
  packages/Card/package.json
  packages/Dropdown/CHANGELOG.md
  packages/Dropdown/Dropdown.jsx
  packages/Dropdown/Dropdown.stories.js
  packages/Dropdown/__tests__/__snapshots__/Dropdown.spec.jsx.snap
  packages/Dropdown/package-lock.json
  packages/Dropdown/package.json
Labels: update

#14 chore(other): removed vulnerabilities
  package-lock.json
  package.json
Labels: dependency
